### ISSUE TITLE
Project layout and planning

### ISSUE THREAD

**Issue by floogulinc** [HexxiumCreations/threat-list-extension#1]
We need to discuss the project's layout and plan how it will be created.

**Comment by floogulinc** [comment]
I think both projects should be able to get their block list from the same list that is used for those with adblock extensions.

For the extension, I think we can either take parts from uBlock Origin or similar and pretty much make a light version of it or possible use something like [this library](https://github.com/bbondy/abp-filter-parser) to parse the block list against websites visited and do the display of the blocked message and such ourselves.

**Comment by Hexxium** [comment]
Closed until we have more conversations about this
