### ISSUE TITLE
We need a name

### ISSUE THREAD

**Issue by Gilbert142** [HexxiumCreations/threat-list-extension#5]
**We are in huge need of a name.**
So far we can choose from:
1. Scammer blocker
2. Malware shield
3. Malicious shield

**Comment by realshaunoneill** [comment]
I dont like malicious shield, something about it makes me seem like it doesn't make sence

**Comment by floogulinc** [comment]
maybe something like `Hexxium Threat List` or `Hexxium Threat Block`.

**Comment by realshaunoneill** [comment]
Not in a bad way towards Hex but i dont think it should be branded his name cause if he ever changed his name etc

**Comment by Hexxium** [comment]
"Anti-Threat" - Or "Hexxium Anti-Threat" if you want to brand it

**Comment by jeremytraini** [comment]
Scam Protector?

**Comment by jeremytraini** [comment]
Scam Killer?

**Comment by ZokiYT** [comment]
Hexxium Web Protector

**Comment by spannercodes** [comment]
Maybe **HexBlock** although that does sound like a lego rip-off.

**Comment by Hexxium** [comment]
Standardized naming scheme works
